const KEY='sitepulse_v03';
let state=JSON.parse(localStorage.getItem(KEY)||'null')||{lang:'en',company:{name:'',prepared:'',logo:''},projects:[],daily:[],punch:[]};
const $=id=>document.getElementById(id),today=()=>new Date().toISOString().slice(0,10),uid=p=>p+'_'+Date.now().toString(36)+Math.random().toString(36).slice(2,6),esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
let lang=state.lang||'en';

const I18N={
 en:{tagline:'Field reports & punch lists',backup:'Backup',restore:'Restore',dashboard:'Dashboard',projects:'Projects',dailyReport:'Daily Report',punchList:'Punch List',pdfPreview:'PDF Preview',company:'Company',hero:'Field reporting without spreadsheet chaos.',heroSub:'A lightweight bilingual workflow for small contractors, maintenance teams, supervisors and inspectors.',openPunch:'Open punch items',dailyReports:'Daily reports',activeProject:'Active project',validationStage:'Validation stage',localNotice:'This MVP stores information locally in each browser. Cloud sync comes after workflow validation.',createProject:'Create project',projectName:'Project name',client:'Client',location:'Location',projectCode:'Project code',notes:'Notes',addProject:'Add project',dailySiteReport:'Daily Site Report',project:'Project',date:'Date',shift:'Shift',day:'Day',night:'Night',preparedBy:'Prepared by',manpower:'Manpower',equipment:'Equipment',workCompleted:'Work completed',materialsDeliveries:'Materials / deliveries',issuesDelays:'Issues / delays',safetyPTW:'Safety / PTW',inspectionQAQC:'Inspection / QA-QC',nextPlan:'Next plan',saveDaily:'Save daily report',savedDaily:'Saved daily reports',addPunch:'Add punch item',status:'Status',priority:'Priority',open:'Open',inProgress:'In Progress',closed:'Closed',low:'Low',medium:'Medium',high:'High',discipline:'Discipline',areaLocation:'Area / location',assignedTo:'Assigned to',issueDescription:'Issue description',actionRequired:'Action required',photo:'Photo',allStatuses:'All statuses',printPdf:'Print / Save PDF',projectPunchReport:'Project Punch List Report',punchSummary:'Punch list summary',items:'Items',companyBranding:'Company branding',companyName:'Company name',preparedDefault:'Prepared by default',companyLogo:'Company logo',saveCompany:'Save company settings',backupNotice:'Use Backup regularly. This validation build stores data in this browser only.',footer:'SitePulse Iraq • Early MVP / market validation',noProject:'No project selected.',noProjects:'No projects yet.',delete:'Delete',deleteProjectConfirm:'Delete project and related data?',createFirst:'Create a project first',enterProject:'Enter project name',noDaily:'No saved reports.',enterIssue:'Enter issue description',noPunch:'No matching punch items.',action:'Action',assigned:'Assigned',saveOk:'Saved',invalidBackup:'Invalid backup file',reportDate:'Report date',total:'Total',area:'Area',description:'Description',noReportItems:'No punch items for this project.'},
 ar:{tagline:'تقارير الموقع وPunch List',backup:'نسخة احتياطية',restore:'استرجاع',dashboard:'لوحة التحكم',projects:'المشاريع',dailyReport:'التقرير اليومي',punchList:'Punch List',pdfPreview:'معاينة PDF',company:'الشركة',hero:'تقارير الموقع بدون فوضى ملفات الإكسل.',heroSub:'نظام خفيف ثنائي اللغة للمقاولين الصغار وفرق الصيانة والمشرفين والمفتشين.',openPunch:'Punch مفتوحة',dailyReports:'تقارير يومية',activeProject:'المشروع الحالي',validationStage:'مرحلة الاختبار',localNotice:'هذه النسخة تحفظ البيانات محلياً داخل كل متصفح. المزامنة السحابية تأتي بعد التحقق من الـworkflow.',createProject:'إنشاء مشروع',projectName:'اسم المشروع',client:'العميل',location:'الموقع',projectCode:'كود المشروع',notes:'ملاحظات',addProject:'إضافة المشروع',dailySiteReport:'التقرير اليومي للموقع',project:'المشروع',date:'التاريخ',shift:'الشفت',day:'نهاري',night:'ليلي',preparedBy:'معد التقرير',manpower:'العمالة',equipment:'المعدات',workCompleted:'الأعمال المنجزة',materialsDeliveries:'المواد / الاستلامات',issuesDelays:'المشاكل / التأخيرات',safetyPTW:'السلامة / PTW',inspectionQAQC:'الفحص / QA-QC',nextPlan:'الخطة القادمة',saveDaily:'حفظ التقرير اليومي',savedDaily:'التقارير اليومية المحفوظة',addPunch:'إضافة Punch Item',status:'الحالة',priority:'الأولوية',open:'مفتوح',inProgress:'قيد التنفيذ',closed:'مغلق',low:'منخفضة',medium:'متوسطة',high:'عالية',discipline:'التخصص',areaLocation:'المنطقة / الموقع',assignedTo:'مسند إلى',issueDescription:'وصف المشكلة',actionRequired:'الإجراء المطلوب',photo:'الصورة',allStatuses:'كل الحالات',printPdf:'طباعة / حفظ PDF',projectPunchReport:'تقرير Punch List للمشروع',punchSummary:'ملخص Punch List',items:'العناصر',companyBranding:'هوية الشركة',companyName:'اسم الشركة',preparedDefault:'معد التقرير الافتراضي',companyLogo:'شعار الشركة',saveCompany:'حفظ إعدادات الشركة',backupNotice:'استخدم النسخة الاحتياطية دورياً. هذه النسخة التجريبية تحفظ البيانات في هذا المتصفح فقط.',footer:'SitePulse Iraq • نسخة أولية لاختبار السوق',noProject:'لا يوجد مشروع محدد.',noProjects:'لا توجد مشاريع بعد.',delete:'حذف',deleteProjectConfirm:'حذف المشروع وكل بياناته المرتبطة؟',createFirst:'أنشئ مشروعاً أولاً',enterProject:'أدخل اسم المشروع',noDaily:'لا توجد تقارير محفوظة.',enterIssue:'أدخل وصف المشكلة',noPunch:'لا توجد عناصر مطابقة.',action:'الإجراء',assigned:'مسند إلى',saveOk:'تم الحفظ',invalidBackup:'ملف النسخة الاحتياطية غير صالح',reportDate:'تاريخ التقرير',total:'الإجمالي',area:'المنطقة',description:'الوصف',noReportItems:'لا توجد عناصر Punch لهذا المشروع.'}
};
const tr=k=>I18N[lang][k]||I18N.en[k]||k;
const statusText=s=>s==='Open'?tr('open'):s==='In Progress'?tr('inProgress'):s==='Closed'?tr('closed'):s;
const priorityText=p=>p==='Low'?tr('low'):p==='Medium'?tr('medium'):p==='High'?tr('high'):p;

function save(){localStorage.setItem(KEY,JSON.stringify(state));renderAll()}
function activeId(){return localStorage.getItem('sp_active')||state.projects[0]?.id||''}
function setActive(id){localStorage.setItem('sp_active',id);renderAll()}
function project(id){return state.projects.find(p=>p.id===id)}

$('nav').addEventListener('click',e=>{if(!e.target.dataset.view)return;document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));$(e.target.dataset.view).classList.add('active');document.querySelectorAll('nav button').forEach(x=>x.classList.remove('active'));e.target.classList.add('active');if(e.target.dataset.view==='report')renderReport()});

$('addProject').onclick=()=>{if(!$('pName').value.trim())return alert(tr('enterProject'));state.projects.unshift({id:uid('p'),name:$('pName').value.trim(),client:$('pClient').value.trim(),location:$('pLocation').value.trim(),code:$('pCode').value.trim(),notes:$('pNotes').value.trim()});setActive(state.projects[0].id);['pName','pClient','pLocation','pCode','pNotes'].forEach(id=>$(id).value='');save()};
function renderProjects(){let box=$('projectList');box.innerHTML=state.projects.length?state.projects.map(p=>`<div class="item"><div class="itemtop"><div onclick="setActive('${p.id}')" style="cursor:pointer"><b>${esc(p.name)}</b><small>${esc(p.client||'—')} • ${esc(p.location||'—')}</small></div><button class="secondary" onclick="delProject('${p.id}')">${tr('delete')}</button></div></div>`).join(''):`<p class="muted">${tr('noProjects')}</p>`}
window.setActive=setActive;window.delProject=id=>{if(!confirm(tr('deleteProjectConfirm')))return;state.projects=state.projects.filter(x=>x.id!==id);state.daily=state.daily.filter(x=>x.projectId!==id);state.punch=state.punch.filter(x=>x.projectId!==id);save()};

function fillSelects(){['dProject','iProject','filterProject','reportProject'].forEach(id=>{let el=$(id),cur=el.value,html=id==='filterProject'?`<option value="All">${tr('projects')}</option>`:'';html+=state.projects.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('');el.innerHTML=html||`<option value="">${tr('createFirst')}</option>`;if([...el.options].some(o=>o.value===cur))el.value=cur;else if([...el.options].some(o=>o.value===activeId()))el.value=activeId()})}

$('saveDaily').onclick=()=>{if(!$('dProject').value)return alert(tr('createFirst'));state.daily.unshift({id:uid('d'),projectId:$('dProject').value,date:$('dDate').value||today(),shift:$('dShift').value,prepared:$('dPrepared').value.trim(),manpower:$('dManpower').value,equipment:$('dEquipment').value.trim(),work:$('dWork').value.trim(),materials:$('dMaterials').value.trim(),issues:$('dIssues').value.trim(),safety:$('dSafety').value.trim(),inspection:$('dInspection').value.trim(),next:$('dNext').value.trim()});['dManpower','dEquipment','dWork','dMaterials','dIssues','dSafety','dInspection','dNext'].forEach(id=>$(id).value='');save()};
function renderDaily(){$('dailyList').innerHTML=state.daily.length?state.daily.slice(0,30).map(r=>`<div class="item"><div class="itemtop"><div><b>${esc(project(r.projectId)?.name||'—')}</b><small>${esc(r.date)} • ${r.shift==='Day'?tr('day'):tr('night')} • ${esc(r.prepared||'—')}</small>${r.work?`<div>${esc(r.work)}</div>`:''}</div><button class="secondary" onclick="delDaily('${r.id}')">${tr('delete')}</button></div></div>`).join(''):`<p class="muted">${tr('noDaily')}</p>`}
window.delDaily=id=>{state.daily=state.daily.filter(x=>x.id!==id);save()};

async function imageData(file,max=900){if(!file)return'';let raw=await new Promise((r,j)=>{let f=new FileReader;f.onload=()=>r(f.result);f.onerror=j;f.readAsDataURL(file)}),im=await new Promise((r,j)=>{let x=new Image;x.onload=()=>r(x);x.onerror=j;x.src=raw}),ratio=Math.min(1,max/Math.max(im.width,im.height)),c=document.createElement('canvas');c.width=Math.round(im.width*ratio);c.height=Math.round(im.height*ratio);c.getContext('2d').drawImage(im,0,0,c.width,c.height);return c.toDataURL('image/jpeg',.72)}
$('addPunch').onclick=async()=>{if(!$('iProject').value)return alert(tr('createFirst'));if(!$('iDesc').value.trim())return alert(tr('enterIssue'));state.punch.unshift({id:uid('i'),projectId:$('iProject').value,status:$('iStatus').value,priority:$('iPriority').value,category:$('iCategory').value.trim(),area:$('iArea').value.trim(),assigned:$('iAssigned').value.trim(),desc:$('iDesc').value.trim(),action:$('iAction').value.trim(),photo:await imageData($('iPhoto').files[0]),created:today()});['iCategory','iArea','iAssigned','iDesc','iAction'].forEach(id=>$(id).value='');$('iPhoto').value='';save()};
$('filterProject').onchange=renderPunch;$('filterStatus').onchange=renderPunch;
function renderPunch(){let fp=$('filterProject').value||'All',fs=$('filterStatus').value||'All',arr=state.punch.filter(x=>(fp==='All'||x.projectId===fp)&&(fs==='All'||x.status===fs));$('punchList').innerHTML=arr.length?arr.map(x=>`<div class="item"><div class="itemtop"><div><span class="pill ${x.status==='Closed'?'closed':x.status==='Open'?'open':'progress'}">${statusText(x.status)}</span><span class="pill ${x.priority.toLowerCase()}">${priorityText(x.priority)}</span><b style="display:block;margin-top:7px">${esc(x.desc)}</b><small>${esc(project(x.projectId)?.name||'—')} • ${esc(x.area||'—')} • ${esc(x.category||'—')}</small>${x.action?`<p><span class="muted">${tr('action')}:</span> ${esc(x.action)}</p>`:''}${x.assigned?`<small>${tr('assigned')}: ${esc(x.assigned)}</small>`:''}${x.photo?`<img class="thumb" src="${x.photo}">`:''}<div class="toolbar"><button class="secondary" onclick="setStatus('${x.id}','Open')">${tr('open')}</button><button class="secondary" onclick="setStatus('${x.id}','In Progress')">${tr('inProgress')}</button><button class="secondary" onclick="setStatus('${x.id}','Closed')">${tr('closed')}</button></div></div><button class="secondary" onclick="delPunch('${x.id}')">${tr('delete')}</button></div></div>`).join(''):`<p class="muted">${tr('noPunch')}</p>`}
window.setStatus=(id,status)=>{let x=state.punch.find(i=>i.id===id);if(x){x.status=status;save()}};window.delPunch=id=>{if(confirm(tr('delete')+'?')){state.punch=state.punch.filter(x=>x.id!==id);save()}};

$('saveCompany').onclick=async()=>{state.company.name=$('cName').value.trim();state.company.prepared=$('cPrepared').value.trim();if($('cLogo').files[0])state.company.logo=await imageData($('cLogo').files[0],700);save();alert(tr('saveOk'))};
function renderReport(){let pid=$('reportProject').value||activeId(),p=project(pid),items=state.punch.filter(x=>x.projectId===pid);$('rCompany').textContent=state.company.name||'SitePulse Client Company';$('rProjectName').textContent=p?.name||'—';$('rDate').textContent=today();if(state.company.logo){$('rLogo').src=state.company.logo;$('rLogo').style.display='block'}else $('rLogo').style.display='none';$('rMeta').innerHTML=`<div><b>${tr('client')}:</b> ${esc(p?.client||'—')}</div><div><b>${tr('location')}:</b> ${esc(p?.location||'—')}</div><div><b>${tr('projectCode')}:</b> ${esc(p?.code||'—')}</div><div><b>${tr('reportDate')}:</b> ${today()}</div>`;let open=items.filter(x=>x.status==='Open').length,prog=items.filter(x=>x.status==='In Progress').length,closed=items.filter(x=>x.status==='Closed').length;$('rSummary').innerHTML=`<div><b>${tr('open')}:</b> ${open}</div><div><b>${tr('inProgress')}:</b> ${prog}</div><div><b>${tr('closed')}:</b> ${closed}</div><div><b>${tr('total')}:</b> ${items.length}</div>`;$('rItems').innerHTML=items.length?`<table><thead><tr><th>#</th><th>${tr('status')}</th><th>${tr('priority')}</th><th>${tr('area')}</th><th>${tr('description')}</th><th>${tr('action')}</th></tr></thead><tbody>${items.map((x,i)=>`<tr><td>${i+1}</td><td>${statusText(x.status)}</td><td>${priorityText(x.priority)}</td><td>${esc(x.area||'—')}</td><td>${esc(x.desc)}${x.photo?`<br><img src="${x.photo}">`:''}</td><td>${esc(x.action||'—')}</td></tr>`).join('')}</tbody></table>`:`<p>${tr('noReportItems')}</p>`}
$('reportProject').onchange=renderReport;$('printReport').onclick=()=>window.print();

$('backupBtn').onclick=()=>{let a=document.createElement('a'),b=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});a.href=URL.createObjectURL(b);a.download='sitepulse-backup-'+today()+'.json';a.click();URL.revokeObjectURL(a.href)};
$('restoreFile').onchange=e=>{let f=e.target.files[0];if(!f)return;let r=new FileReader;r.onload=()=>{try{state=JSON.parse(r.result);lang=state.lang||'en';save();applyLang()}catch{alert(tr('invalidBackup'))}};r.readAsText(f)};

$('langBtn').onclick=()=>{lang=lang==='en'?'ar':'en';state.lang=lang;localStorage.setItem(KEY,JSON.stringify(state));applyLang();renderAll()};
function applyLang(){document.documentElement.lang=lang;document.documentElement.dir=lang==='ar'?'rtl':'ltr';$('langBtn').textContent=lang==='en'?'العربية':'English';document.querySelectorAll('[data-i18n]').forEach(el=>{let key=el.dataset.i18n;if(I18N[lang][key])el.textContent=I18N[lang][key]})}
function renderAll(){fillSelects();renderProjects();renderDaily();renderPunch();$('sProjects').textContent=state.projects.length;$('sOpen').textContent=state.punch.filter(x=>x.status!=='Closed').length;$('sDaily').textContent=state.daily.length;let p=project(activeId());$('activeProject').innerHTML=p?`<b>${esc(p.name)}</b><small>${esc(p.client||'—')} • ${esc(p.location||'—')}</small>`:tr('noProject');$('cName').value=state.company.name||'';$('cPrepared').value=state.company.prepared||'';if(!$('dPrepared').value)$('dPrepared').value=state.company.prepared||'';renderReport()}
$('dDate').value=today();applyLang();renderAll();
