(()=>{
  const KEY='sitepulse_v03';
  const q=new URLSearchParams(location.search);
  const reportId=q.get('id')||'';
  let state={};
  try{state=JSON.parse(localStorage.getItem(KEY)||'{}')}catch{}
  const report=(state.daily||[]).find(r=>r.id===reportId);
  const project=(state.projects||[]).find(p=>p.id===report?.projectId)||{};
  const company=state.company||{};
  let lang=q.get('lang')||state.lang||'en';
  if(!['en','ar'].includes(lang))lang='en';
  const $=id=>document.getElementById(id);
  const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  const text=v=>String(v??'').trim()||'—';
  const T={
    en:{title:'DAILY SITE REPORT',project:'Project',client:'Client',location:'Location',code:'Project code',date:'Date',shift:'Shift',prepared:'Prepared by',manpower:'Manpower',equipment:'Equipment',work:'Work completed',materials:'Materials / deliveries',issues:'Issues / delays',safety:'Safety / PTW',inspection:'Inspection / QA-QC',next:'Next plan',reviewed:'Reviewed by',generated:'Generated by SitePulse Iraq',footer:'SitePulse Iraq - Daily Site Report',print:'Print / Save PDF',email:'Prepare Email',back:'Back to SitePulse',help:'For a clean PDF: choose A4 and turn off browser headers & footers.',day:'Day',night:'Night',missing:'Daily report not found on this device.'},
    ar:{title:'التقرير اليومي للموقع',project:'المشروع',client:'العميل',location:'الموقع',code:'كود المشروع',date:'التاريخ',shift:'الشفت',prepared:'معد التقرير',manpower:'العمالة',equipment:'المعدات',work:'الأعمال المنجزة',materials:'المواد / الاستلامات',issues:'المشاكل / التأخيرات',safety:'السلامة / PTW',inspection:'الفحص / QA-QC',next:'الخطة القادمة',reviewed:'تمت المراجعة بواسطة',generated:'تم الإنشاء بواسطة SitePulse Iraq',footer:'SitePulse Iraq - التقرير اليومي للموقع',print:'طباعة / حفظ PDF',email:'تحضير الإيميل',back:'العودة إلى SitePulse',help:'للحصول على PDF مرتب: اختر A4 وأوقف رؤوس وتذييلات المتصفح.',day:'نهاري',night:'ليلي',missing:'التقرير اليومي غير موجود على هذا الجهاز.'}
  };
  const tr=k=>T[lang][k]||T.en[k]||k;

  function setLang(){
    document.documentElement.lang=lang;
    document.documentElement.dir=lang==='ar'?'rtl':'ltr';
    document.body.classList.toggle('rtl',lang==='ar');
    $('langToggle').textContent=lang==='en'?'العربية':'English';
    $('printReport').textContent=tr('print');
    $('emailReport').textContent=tr('email');
    document.querySelector('.toolbar a').textContent=tr('back');
    $('printHelp').textContent=tr('help');
  }

  function meta(label,value,full=false){return `<div class="meta${full?' full':''}"><div class="label">${esc(label)}</div><div class="value">${esc(text(value))}</div></div>`}
  function section(title,body){const v=String(body??'').trim();return `<section class="report-section"><div class="section-title">${esc(title)}</div><div class="section-body${v?'':' empty'}">${esc(v||'—')}</div></section>`}

  function render(){
    setLang();
    if(!report){$('reportRoot').hidden=true;$('reportError').hidden=false;$('reportError').textContent=tr('missing');return}
    $('reportRoot').hidden=false;$('reportError').hidden=true;
    const displayShift=report.shift==='Night'?tr('night'):tr('day');
    const shortId=String(report.id||'').slice(-6).toUpperCase();
    const reportNo=`DSR-${report.date||''}-${shortId}`;
    document.title=`Daily Site Report - ${project.name||'Project'} - ${report.date||''}`;
    $('companyName').textContent=company.name||'SitePulse Client Company';
    $('reportTitle').textContent=tr('title');
    $('reportNumber').textContent=reportNo;
    $('generatedBy').textContent=tr('generated');
    $('preparedLabel').textContent=tr('prepared');
    $('reviewedLabel').textContent=tr('reviewed');
    $('preparedValue').textContent=report.prepared||company.prepared||'—';
    $('footerLeft').textContent=tr('footer');
    $('footerRight').textContent=reportNo;
    if(company.logo){$('companyLogo').src=company.logo;$('companyLogo').style.display='block'}else $('companyLogo').style.display='none';
    $('metaGrid').innerHTML=[
      meta(tr('project'),project.name),meta(tr('client'),project.client),meta(tr('location'),project.location),meta(tr('code'),project.code),
      meta(tr('date'),report.date),meta(tr('shift'),displayShift),meta(tr('prepared'),report.prepared||company.prepared),meta(tr('manpower'),report.manpower),meta(tr('equipment'),report.equipment,true)
    ].join('');
    $('reportSections').innerHTML=[
      section(tr('work'),report.work),section(tr('materials'),report.materials),section(tr('issues'),report.issues),section(tr('safety'),report.safety),section(tr('inspection'),report.inspection),section(tr('next'),report.next)
    ].join('');
  }

  async function track(event){
    try{
      let visitorId=localStorage.getItem('sp_visitor_id')||'';
      if(!visitorId){visitorId='v_'+(crypto.randomUUID?crypto.randomUUID():Math.random().toString(36).slice(2));localStorage.setItem('sp_visitor_id',visitorId)}
      let sessionId=sessionStorage.getItem('sp_session_id')||'';
      if(!sessionId){sessionId='s_'+(crypto.randomUUID?crypto.randomUUID():Math.random().toString(36).slice(2));sessionStorage.setItem('sp_session_id',sessionId)}
      let profile={};try{profile=JSON.parse(localStorage.getItem('sp_tester_profile')||'{}')}catch{}
      await fetch('/.netlify/functions/analytics-event',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({event,visitorId,sessionId,testerName:profile.name||'',testerRole:profile.role||'',source:'',campaign:'',lang}),keepalive:true});
    }catch{}
  }

  $('langToggle').onclick=()=>{lang=lang==='en'?'ar':'en';q.set('lang',lang);history.replaceState(null,'',location.pathname+'?'+q.toString());render()};
  $('printReport').onclick=()=>{track('pdf_exported');window.print()};
  $('emailReport').onclick=()=>{
    track('email_prepared');
    if(!report)return;
    const subject=`Daily Site Report - ${project.name||'Project'} - ${report.date||''}`;
    const body=`Dear Team,\n\nPlease find attached the Daily Site Report for ${project.name||'the project'} dated ${report.date||''}.\n\nRegards,\n${report.prepared||company.prepared||''}`;
    location.href=`mailto:?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;
  };
  track('daily_pdf_opened');
  render();
})();
